//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OIMS.Views.Shared.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;serverConfirm&quot; class=&quot;alert alert-info fade in&quot;&gt;
        ///        &lt;button class=&quot;close&quot; data-dismiss=&quot;alert&quot; formnovalidate&gt;x&lt;/button&gt;
        ///        {0}
        ///    &lt;/div&gt;.
        /// </summary>
        public static string ConfirmDiv {
            get {
                return ResourceManager.GetString("ConfirmDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Oops! An unexpected error occured while processing your request.&lt;/p&gt;.
        /// </summary>
        public static string ErrorContent {
            get {
                return ResourceManager.GetString("ErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;serverError&quot; class=&quot;validation-summary-errors&quot;&gt;
        ///    &lt;b&gt;Error -&lt;/b&gt; {0}
        ///&lt;/div&gt;.
        /// </summary>
        public static string ErrorDiv {
            get {
                return ResourceManager.GetString("ErrorDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        public static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of fields are still blank..
        /// </summary>
        public static string ErrorMsgBlankFields {
            get {
                return ResourceManager.GetString("ErrorMsgBlankFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, correct all errors..
        /// </summary>
        public static string ErrorMsgForGrid {
            get {
                return ResourceManager.GetString("ErrorMsgForGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired. Please try again after re-login..
        /// </summary>
        public static string ErrorMsgForSession {
            get {
                return ResourceManager.GetString("ErrorMsgForSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request details for selected request id not found..
        /// </summary>
        public static string ErrorMsgReqNotFound {
            get {
                return ResourceManager.GetString("ErrorMsgReqNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; {0} Inventory Department. All rights reserved..
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClinicalStudyTheme.
        /// </summary>
        public static string GlobalTheme {
            get {
                return ResourceManager.GetString("GlobalTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lib/license.lic.
        /// </summary>
        public static string LicensePath {
            get {
                return ResourceManager.GetString("LicensePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! Opening page....
        /// </summary>
        public static string LoaderMsg {
            get {
                return ResourceManager.GetString("LoaderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Inventory Management System.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevEx.
        /// </summary>
        public static string ReportTheme {
            get {
                return ResourceManager.GetString("ReportTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua.
        /// </summary>
        public static string SubTheme {
            get {
                return ResourceManager.GetString("SubTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial mode expired.
        /// </summary>
        public static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0} !.
        /// </summary>
        public static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
    }
}
