//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Requestor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Requestor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OIMS.Views.Requestor.Requestor", typeof(Requestor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Nr_ButtonCancel {
            get {
                return ResourceManager.GetString("Nr_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Nr_ButtonDefault {
            get {
                return ResourceManager.GetString("Nr_ButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Nr_ButtonSave {
            get {
                return ResourceManager.GetString("Nr_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job cannot be blank..
        /// </summary>
        public static string Nr_ErrorMsgJobEmpty {
            get {
                return ResourceManager.GetString("Nr_ErrorMsgJobEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name was not provided..
        /// </summary>
        public static string Nr_ErrorMsgNoCompany {
            get {
                return ResourceManager.GetString("Nr_ErrorMsgNoCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job name was not provided (or selected)..
        /// </summary>
        public static string Nr_ErrorMsgNoJob {
            get {
                return ResourceManager.GetString("Nr_ErrorMsgNoJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.No..
        /// </summary>
        public static string Nr_GridId {
            get {
                return ResourceManager.GetString("Nr_GridId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string Nr_GridItemName {
            get {
                return ResourceManager.GetString("Nr_GridItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking.
        /// </summary>
        public static string Nr_GridMarking {
            get {
                return ResourceManager.GetString("Nr_GridMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity/Shelter.
        /// </summary>
        public static string Nr_GridQtyPerShelter {
            get {
                return ResourceManager.GetString("Nr_GridQtyPerShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Quantity.
        /// </summary>
        public static string Nr_GridQuantity {
            get {
                return ResourceManager.GetString("Nr_GridQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Nr_GridSize {
            get {
                return ResourceManager.GetString("Nr_GridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string Nr_Header {
            get {
                return ResourceManager.GetString("Nr_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Nr_Items {
            get {
                return ResourceManager.GetString("Nr_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job named &lt;b&gt;{0}&lt;/b&gt; will be associated to all new requests..
        /// </summary>
        public static string Nr_JobNotice {
            get {
                return ResourceManager.GetString("Nr_JobNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your request(s).
        /// </summary>
        public static string Nr_Legend {
            get {
                return ResourceManager.GetString("Nr_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! Adding to cart...
        /// </summary>
        public static string Nr_Loader {
            get {
                return ResourceManager.GetString("Nr_Loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Nr_PopLoader {
            get {
                return ResourceManager.GetString("Nr_PopLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set job and company for requests.
        /// </summary>
        public static string Nr_PopupHeader {
            get {
                return ResourceManager.GetString("Nr_PopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new job.
        /// </summary>
        public static string Nr_RadioFirst {
            get {
                return ResourceManager.GetString("Nr_RadioFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an existing job.
        /// </summary>
        public static string Nr_RadioSecond {
            get {
                return ResourceManager.GetString("Nr_RadioSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select item:.
        /// </summary>
        public static string Nr_SelectItem {
            get {
                return ResourceManager.GetString("Nr_SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shelter:.
        /// </summary>
        public static string Nr_SelectShelter {
            get {
                return ResourceManager.GetString("Nr_SelectShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelters.
        /// </summary>
        public static string Nr_Shelters {
            get {
                return ResourceManager.GetString("Nr_Shelters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIMS - Requestor zone.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no item for adding to cart..
        /// </summary>
        public static string Req_Cart_ErrorNoItem {
            get {
                return ResourceManager.GetString("Req_Cart_ErrorNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no shelter for adding to cart..
        /// </summary>
        public static string Req_Cart_ErrorNoShelter {
            get {
                return ResourceManager.GetString("Req_Cart_ErrorNoShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added to cart successfully..
        /// </summary>
        public static string Req_Cart_ItemAdded {
            get {
                return ResourceManager.GetString("Req_Cart_ItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart item deleted successfully..
        /// </summary>
        public static string Req_Cart_MaterialDelete {
            get {
                return ResourceManager.GetString("Req_Cart_MaterialDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was sent successfully! You can check same from &apos;Requests&apos; tab..
        /// </summary>
        public static string Req_Cart_MaterialSaved {
            get {
                return ResourceManager.GetString("Req_Cart_MaterialSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter added to cart successfully..
        /// </summary>
        public static string Req_Cart_ShelterAdded {
            get {
                return ResourceManager.GetString("Req_Cart_ShelterAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date:.
        /// </summary>
        public static string Req_Date {
            get {
                return ResourceManager.GetString("Req_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string Req_DateNA {
            get {
                return ResourceManager.GetString("Req_DateNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended:.
        /// </summary>
        public static string Req_Detail_Recommend {
            get {
                return ResourceManager.GetString("Req_Detail_Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested:.
        /// </summary>
        public static string Req_Detail_Request {
            get {
                return ResourceManager.GetString("Req_Detail_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string Req_Grid_DateFormat {
            get {
                return ResourceManager.GetString("Req_Grid_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Req_GridCompany {
            get {
                return ResourceManager.GetString("Req_GridCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Date.
        /// </summary>
        public static string Req_GridDate {
            get {
                return ResourceManager.GetString("Req_GridDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No request(s) found..
        /// </summary>
        public static string Req_GridEmptyMsg {
            get {
                return ResourceManager.GetString("Req_GridEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Id.
        /// </summary>
        public static string Req_GridId {
            get {
                return ResourceManager.GetString("Req_GridId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach to Job.
        /// </summary>
        public static string Req_GridJob {
            get {
                return ResourceManager.GetString("Req_GridJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Req_GridStatus {
            get {
                return ResourceManager.GetString("Req_GridStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Id:.
        /// </summary>
        public static string Req_Id {
            get {
                return ResourceManager.GetString("Req_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click respective request for more details..
        /// </summary>
        public static string Req_Info {
            get {
                return ResourceManager.GetString("Req_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not updated yet.
        /// </summary>
        public static string Req_NameNA {
            get {
                return ResourceManager.GetString("Req_NameNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By:.
        /// </summary>
        public static string Req_RequestedBy {
            get {
                return ResourceManager.GetString("Req_RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Company --.
        /// </summary>
        public static string Req_SelectCompanyOption {
            get {
                return ResourceManager.GetString("Req_SelectCompanyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Job --.
        /// </summary>
        public static string Req_SelectJobOption {
            get {
                return ResourceManager.GetString("Req_SelectJobOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status:.
        /// </summary>
        public static string Req_Status {
            get {
                return ResourceManager.GetString("Req_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated By:.
        /// </summary>
        public static string Req_UpdateBy {
            get {
                return ResourceManager.GetString("Req_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date:.
        /// </summary>
        public static string Req_UpdateDate {
            get {
                return ResourceManager.GetString("Req_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Sb_Btn_Remove {
            get {
                return ResourceManager.GetString("Sb_Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Sb_Btn_Submit {
            get {
                return ResourceManager.GetString("Sb_Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty..
        /// </summary>
        public static string Sb_NoShelter {
            get {
                return ResourceManager.GetString("Sb_NoShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request List.
        /// </summary>
        public static string Sb_ReqList {
            get {
                return ResourceManager.GetString("Sb_ReqList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count:.
        /// </summary>
        public static string Sb_TotalCount {
            get {
                return ResourceManager.GetString("Sb_TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string TabNewRequest {
            get {
                return ResourceManager.GetString("TabNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string TabRequests {
            get {
                return ResourceManager.GetString("TabRequests", resourceCulture);
            }
        }
    }
}
