//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Supervisor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Supervisor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OIMS.Views.Supervisor.Supervisor", typeof(Supervisor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character should be less than 200.
        /// </summary>
        public static string ErrorMsgCharLimit {
            get {
                return ResourceManager.GetString("ErrorMsgCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string GridCommand {
            get {
                return ResourceManager.GetString("GridCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string IBtnAdd {
            get {
                return ResourceManager.GetString("IBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item(s).
        /// </summary>
        public static string IBtnNewItem {
            get {
                return ResourceManager.GetString("IBtnNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all items.
        /// </summary>
        public static string IBtnSave {
            get {
                return ResourceManager.GetString("IBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is being used in shelter. First delete shelter using item &apos;{0}&apos;.
        /// </summary>
        public static string IErrorMsgItemBeingUse {
            get {
                return ResourceManager.GetString("IErrorMsgItemBeingUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more item(s) with same name already exists in database. Please modify items list. You can edit stock directly from items grid..
        /// </summary>
        public static string IErrorMsgItemExist {
            get {
                return ResourceManager.GetString("IErrorMsgItemExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with same name already exists..
        /// </summary>
        public static string IErrorMsgItemExists {
            get {
                return ResourceManager.GetString("IErrorMsgItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name is required.
        /// </summary>
        public static string IErrorMsgItemName {
            get {
                return ResourceManager.GetString("IErrorMsgItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is required.
        /// </summary>
        public static string IErrorMsgItemQty {
            get {
                return ResourceManager.GetString("IErrorMsgItemQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking is required.
        /// </summary>
        public static string IErrorMsgMarking {
            get {
                return ResourceManager.GetString("IErrorMsgMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items with same name cannot be added to database..
        /// </summary>
        public static string IErrorMsgSameItem {
            get {
                return ResourceManager.GetString("IErrorMsgSameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of item is required.
        /// </summary>
        public static string IErrorMsgSize {
            get {
                return ResourceManager.GetString("IErrorMsgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to display. Please add new items..
        /// </summary>
        public static string IGridEmptyMsg {
            get {
                return ResourceManager.GetString("IGridEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string IGridItemName {
            get {
                return ResourceManager.GetString("IGridItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking.
        /// </summary>
        public static string IGridMarking {
            get {
                return ResourceManager.GetString("IGridMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units in stock.
        /// </summary>
        public static string IGridQuantity {
            get {
                return ResourceManager.GetString("IGridQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string IGridSize {
            get {
                return ResourceManager.GetString("IGridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated On.
        /// </summary>
        public static string IGridUpdatedOn {
            get {
                return ResourceManager.GetString("IGridUpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Vendor.
        /// </summary>
        public static string IGridVendor {
            get {
                return ResourceManager.GetString("IGridVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string Ih2 {
            get {
                return ResourceManager.GetString("Ih2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all logs.
        /// </summary>
        public static string IL_BtnSave {
            get {
                return ResourceManager.GetString("IL_BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common vendor.
        /// </summary>
        public static string IL_CommonVendor {
            get {
                return ResourceManager.GetString("IL_CommonVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string IL_GridDateFormat {
            get {
                return ResourceManager.GetString("IL_GridDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs to display. Please add new items log..
        /// </summary>
        public static string IL_GridEmptyMsg {
            get {
                return ResourceManager.GetString("IL_GridEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Date.
        /// </summary>
        public static string IL_GridLogDate {
            get {
                return ResourceManager.GetString("IL_GridLogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string IL_GridQuantity {
            get {
                return ResourceManager.GetString("IL_GridQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        public static string IL_GridVendorName {
            get {
                return ResourceManager.GetString("IL_GridVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Log.
        /// </summary>
        public static string IL_h2 {
            get {
                return ResourceManager.GetString("IL_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item(s) log.
        /// </summary>
        public static string IL_LegdItemsLog {
            get {
                return ResourceManager.GetString("IL_LegdItemsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Log.
        /// </summary>
        public static string IL_Logs {
            get {
                return ResourceManager.GetString("IL_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items log saved successfully!.
        /// </summary>
        public static string IL_MsgLogCreated {
            get {
                return ResourceManager.GetString("IL_MsgLogCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item(s).
        /// </summary>
        public static string ILegdItems {
            get {
                return ResourceManager.GetString("ILegdItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! Saving items data....
        /// </summary>
        public static string ILoader {
            get {
                return ResourceManager.GetString("ILoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items saved successfully!.
        /// </summary>
        public static string IMsgItemCreated {
            get {
                return ResourceManager.GetString("IMsgItemCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIMS - Supervisor zone.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string RBtnGo {
            get {
                return ResourceManager.GetString("RBtnGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string RBtnSave {
            get {
                return ResourceManager.GetString("RBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated.
        /// </summary>
        public static string RGridAlloc {
            get {
                return ResourceManager.GetString("RGridAlloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        public static string RGridCount {
            get {
                return ResourceManager.GetString("RGridCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot recommend greater than the requested value..
        /// </summary>
        public static string RGridErrorMsgForExtraRecommend {
            get {
                return ResourceManager.GetString("RGridErrorMsgForExtraRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of Recommend &amp; Allocated should not exceed than Requested..
        /// </summary>
        public static string RGridErrorMsgForPartial {
            get {
                return ResourceManager.GetString("RGridErrorMsgForPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string RGridPending {
            get {
                return ResourceManager.GetString("RGridPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend.
        /// </summary>
        public static string RGridRecom {
            get {
                return ResourceManager.GetString("RGridRecom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        public static string RGridStock {
            get {
                return ResourceManager.GetString("RGridStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click row under &apos;Recommend&apos; for recommending &apos;{0}&apos;.
        /// </summary>
        public static string RGridTooltip {
            get {
                return ResourceManager.GetString("RGridTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click respective request for allocating shelters or items and saving status..
        /// </summary>
        public static string RInfo {
            get {
                return ResourceManager.GetString("RInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait!Updating item stock....
        /// </summary>
        public static string RItemGridLoad {
            get {
                return ResourceManager.GetString("RItemGridLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! Generating report....
        /// </summary>
        public static string RLoader {
            get {
                return ResourceManager.GetString("RLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! Updating shelter stock....
        /// </summary>
        public static string RProdGridLoad {
            get {
                return ResourceManager.GetString("RProdGridLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Shelter --.
        /// </summary>
        public static string RSelectShelterOption {
            get {
                return ResourceManager.GetString("RSelectShelterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Status --.
        /// </summary>
        public static string RSelectStatusOption {
            get {
                return ResourceManager.GetString("RSelectStatusOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SBtnAdd {
            get {
                return ResourceManager.GetString("SBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new shelter.
        /// </summary>
        public static string SBtnSave {
            get {
                return ResourceManager.GetString("SBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item is already associated with current shelter..
        /// </summary>
        public static string SErrorMsgForItemExist {
            get {
                return ResourceManager.GetString("SErrorMsgForItemExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter with same name already exists..
        /// </summary>
        public static string SErrorMsgProductExist {
            get {
                return ResourceManager.GetString("SErrorMsgProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected items should be unique for current shelter..
        /// </summary>
        public static string SErrorMsgSameItem {
            get {
                return ResourceManager.GetString("SErrorMsgSameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shelters to display. Please add new shelters..
        /// </summary>
        public static string SGridEmptyMsg {
            get {
                return ResourceManager.GetString("SGridEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found associated with shelter..
        /// </summary>
        public static string SGridItemEmptyMsg {
            get {
                return ResourceManager.GetString("SGridItemEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of item.
        /// </summary>
        public static string SGridItemName {
            get {
                return ResourceManager.GetString("SGridItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string SGridItemNewLink {
            get {
                return ResourceManager.GetString("SGridItemNewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Shelter.
        /// </summary>
        public static string SGridItemsQtyPerShelter {
            get {
                return ResourceManager.GetString("SGridItemsQtyPerShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        public static string SGridItemStock {
            get {
                return ResourceManager.GetString("SGridItemStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter Name.
        /// </summary>
        public static string SGridProdName {
            get {
                return ResourceManager.GetString("SGridProdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Stock Count.
        /// </summary>
        public static string SGridQuantity {
            get {
                return ResourceManager.GetString("SGridQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string SGridVendor {
            get {
                return ResourceManager.GetString("SGridVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Shelter.
        /// </summary>
        public static string Sh2 {
            get {
                return ResourceManager.GetString("Sh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a item:.
        /// </summary>
        public static string SItemLabel {
            get {
                return ResourceManager.GetString("SItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new shelter.
        /// </summary>
        public static string SLegdProducts {
            get {
                return ResourceManager.GetString("SLegdProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! Saving shelter data....
        /// </summary>
        public static string SLoader {
            get {
                return ResourceManager.GetString("SLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new shelter &apos;{0}&apos; created successfully!.
        /// </summary>
        public static string SMsgProductCreated {
            get {
                return ResourceManager.GetString("SMsgProductCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter shelter name:.
        /// </summary>
        public static string SProductLabel {
            get {
                return ResourceManager.GetString("SProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string TabItems {
            get {
                return ResourceManager.GetString("TabItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Log.
        /// </summary>
        public static string TabItemsLog {
            get {
                return ResourceManager.GetString("TabItemsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string TabReports {
            get {
                return ResourceManager.GetString("TabReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string TabRequests {
            get {
                return ResourceManager.GetString("TabRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelters.
        /// </summary>
        public static string TabShelters {
            get {
                return ResourceManager.GetString("TabShelters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string TabUsers {
            get {
                return ResourceManager.GetString("TabUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string TabVendors {
            get {
                return ResourceManager.GetString("TabVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string UBtnNewUser {
            get {
                return ResourceManager.GetString("UBtnNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new user.
        /// </summary>
        public static string UBtnSave {
            get {
                return ResourceManager.GetString("UBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required.
        /// </summary>
        public static string UErrorMsgConfirmPassword {
            get {
                return ResourceManager.GetString("UErrorMsgConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string UErrorMsgEmail {
            get {
                return ResourceManager.GetString("UErrorMsgEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with same email address already exists..
        /// </summary>
        public static string UErrorMsgEmailExist {
            get {
                return ResourceManager.GetString("UErrorMsgEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string UErrorMsgFirstName {
            get {
                return ResourceManager.GetString("UErrorMsgFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string UErrorMsgLastName {
            get {
                return ResourceManager.GetString("UErrorMsgLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string UErrorMsgPassword {
            get {
                return ResourceManager.GetString("UErrorMsgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is required.
        /// </summary>
        public static string UErrorMsgRole {
            get {
                return ResourceManager.GetString("UErrorMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UGridEmail {
            get {
                return ResourceManager.GetString("UGridEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users to display. Please add new users..
        /// </summary>
        public static string UGridEmptyMsg {
            get {
                return ResourceManager.GetString("UGridEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string UGridFirstName {
            get {
                return ResourceManager.GetString("UGridFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string UGridLastName {
            get {
                return ResourceManager.GetString("UGridLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UGridPassword {
            get {
                return ResourceManager.GetString("UGridPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string UGridRole {
            get {
                return ResourceManager.GetString("UGridRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string Uh2 {
            get {
                return ResourceManager.GetString("Uh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ULblConfirmPass {
            get {
                return ResourceManager.GetString("ULblConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        public static string ULegdLogin {
            get {
                return ResourceManager.GetString("ULegdLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details.
        /// </summary>
        public static string ULegdPersonal {
            get {
                return ResourceManager.GetString("ULegdPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! Saving user data....
        /// </summary>
        public static string ULoader {
            get {
                return ResourceManager.GetString("ULoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user &apos;{0}&apos; created successfully!.
        /// </summary>
        public static string UMsgUserCreated {
            get {
                return ResourceManager.GetString("UMsgUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new vendor.
        /// </summary>
        public static string VBtnNewVendor {
            get {
                return ResourceManager.GetString("VBtnNewVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new vendor.
        /// </summary>
        public static string VBtnSave {
            get {
                return ResourceManager.GetString("VBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string VErrorMsgName {
            get {
                return ResourceManager.GetString("VErrorMsgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor with same name already exists..
        /// </summary>
        public static string VErrorMsgVendorExist {
            get {
                return ResourceManager.GetString("VErrorMsgVendorExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string VGridAddress {
            get {
                return ResourceManager.GetString("VGridAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string VGridEmail {
            get {
                return ResourceManager.GetString("VGridEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vendors to display. Please add new vendors..
        /// </summary>
        public static string VGridEmptyMsg {
            get {
                return ResourceManager.GetString("VGridEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string VGridName {
            get {
                return ResourceManager.GetString("VGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string VGridPhone {
            get {
                return ResourceManager.GetString("VGridPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vendor.
        /// </summary>
        public static string Vh2 {
            get {
                return ResourceManager.GetString("Vh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Details.
        /// </summary>
        public static string VLegd {
            get {
                return ResourceManager.GetString("VLegd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! Saving vendor data....
        /// </summary>
        public static string VLoader {
            get {
                return ResourceManager.GetString("VLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New vendor &apos;{0}&apos; created successfully!.
        /// </summary>
        public static string VMsgVendorCreated {
            get {
                return ResourceManager.GetString("VMsgVendorCreated", resourceCulture);
            }
        }
    }
}
