#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OimsDataModel;


namespace OimsDataModel	
{
	public partial class Cartstuff
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int _u_Id;
		public virtual int U_Id 
		{ 
		    get
		    {
		        return this._u_Id;
		    }
		    set
		    {
		        this._u_Id = value;
		    }
		}
		
		private int? _p_Id;
		public virtual int? P_Id 
		{ 
		    get
		    {
		        return this._p_Id;
		    }
		    set
		    {
		        this._p_Id = value;
		    }
		}
		
		private int? _i_Id;
		public virtual int? I_Id 
		{ 
		    get
		    {
		        return this._i_Id;
		    }
		    set
		    {
		        this._i_Id = value;
		    }
		}
		
		private float _quantity;
		public virtual float Quantity 
		{ 
		    get
		    {
		        return this._quantity;
		    }
		    set
		    {
		        this._quantity = value;
		    }
		}
		
		private DateTime _createdOnUtc;
		public virtual DateTime CreatedOnUtc 
		{ 
		    get
		    {
		        return this._createdOnUtc;
		    }
		    set
		    {
		        this._createdOnUtc = value;
		    }
		}
		
		private Item _item;
		public virtual Item Item 
		{ 
		    get
		    {
		        return this._item;
		    }
		    set
		    {
		        this._item = value;
		    }
		}
		
		private Shelter _shelter;
		public virtual Shelter Shelter 
		{ 
		    get
		    {
		        return this._shelter;
		    }
		    set
		    {
		        this._shelter = value;
		    }
		}
		
		private User _user;
		public virtual User User 
		{ 
		    get
		    {
		        return this._user;
		    }
		    set
		    {
		        this._user = value;
		    }
		}
		
	}
}
