#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OimsDataModel;


namespace OimsDataModel	
{
	public partial class OimsDbContext : OpenAccessContext, IOimsDbContextUnitOfWork
	{
		private static string connectionStringName = @"OimsConString";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntityDiagrams.rlinq");
	
		public OimsDbContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public OimsDbContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public OimsDbContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public OimsDbContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public OimsDbContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Vendor> Vendors 
		{
	    	get
	    	{
	        	return this.GetAll<Vendor>();
	    	}
		}
		
		public IQueryable<User> Users 
		{
	    	get
	    	{
	        	return this.GetAll<User>();
	    	}
		}
		
		public IQueryable<Sheltersrequest> Sheltersrequests 
		{
	    	get
	    	{
	        	return this.GetAll<Sheltersrequest>();
	    	}
		}
		
		public IQueryable<Shelter> Shelters 
		{
	    	get
	    	{
	        	return this.GetAll<Shelter>();
	    	}
		}
		
		public IQueryable<Shelterdescription> Shelterdescriptions 
		{
	    	get
	    	{
	        	return this.GetAll<Shelterdescription>();
	    	}
		}
		
		public IQueryable<Role> Roles 
		{
	    	get
	    	{
	        	return this.GetAll<Role>();
	    	}
		}
		
		public IQueryable<Requeststatus> Requeststatus 
		{
	    	get
	    	{
	        	return this.GetAll<Requeststatus>();
	    	}
		}
		
		public IQueryable<Request> Requests 
		{
	    	get
	    	{
	        	return this.GetAll<Request>();
	    	}
		}
		
		public IQueryable<Itemsrequest> Itemsrequests 
		{
	    	get
	    	{
	        	return this.GetAll<Itemsrequest>();
	    	}
		}
		
		public IQueryable<Itemslog> Itemslogs 
		{
	    	get
	    	{
	        	return this.GetAll<Itemslog>();
	    	}
		}
		
		public IQueryable<Item> Items 
		{
	    	get
	    	{
	        	return this.GetAll<Item>();
	    	}
		}
		
		public IQueryable<Company> Companies 
		{
	    	get
	    	{
	        	return this.GetAll<Company>();
	    	}
		}
		
		public IQueryable<Cartstuff> Cartstuffs 
		{
	    	get
	    	{
	        	return this.GetAll<Cartstuff>();
	    	}
		}
		
		public IQueryable<Allocated> Allocateds 
		{
	    	get
	    	{
	        	return this.GetAll<Allocated>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			return backend;
		}
	}

	public interface IOimsDbContextUnitOfWork : IUnitOfWork
	{
		IQueryable<Vendor> Vendors 
		{ 
			get;
		}

		IQueryable<User> Users 
		{ 
			get;
		}

		IQueryable<Sheltersrequest> Sheltersrequests 
		{ 
			get;
		}

		IQueryable<Shelter> Shelters 
		{ 
			get;
		}

		IQueryable<Shelterdescription> Shelterdescriptions 
		{ 
			get;
		}

		IQueryable<Role> Roles 
		{ 
			get;
		}

		IQueryable<Requeststatus> Requeststatus 
		{ 
			get;
		}

		IQueryable<Request> Requests 
		{ 
			get;
		}

		IQueryable<Itemsrequest> Itemsrequests 
		{ 
			get;
		}

		IQueryable<Itemslog> Itemslogs 
		{ 
			get;
		}

		IQueryable<Item> Items 
		{ 
			get;
		}

		IQueryable<Company> Companies 
		{ 
			get;
		}

		IQueryable<Cartstuff> Cartstuffs 
		{ 
			get;
		}

		IQueryable<Allocated> Allocateds 
		{ 
			get;
		}

	}
}
#pragma warning restore 1591

