#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OimsDataModel;


namespace OimsDataModel	
{
	public partial class Itemslog
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int _itemId;
		public virtual int ItemId 
		{ 
		    get
		    {
		        return this._itemId;
		    }
		    set
		    {
		        this._itemId = value;
		    }
		}
		
		private float _itemQuantity;
		public virtual float ItemQuantity 
		{ 
		    get
		    {
		        return this._itemQuantity;
		    }
		    set
		    {
		        this._itemQuantity = value;
		    }
		}
		
		private string _vendorName;
		public virtual string VendorName 
		{ 
		    get
		    {
		        return this._vendorName;
		    }
		    set
		    {
		        this._vendorName = value;
		    }
		}
		
		private DateTime _entryDate;
		public virtual DateTime EntryDate 
		{ 
		    get
		    {
		        return this._entryDate;
		    }
		    set
		    {
		        this._entryDate = value;
		    }
		}
		
		private Item _item;
		public virtual Item Item 
		{ 
		    get
		    {
		        return this._item;
		    }
		    set
		    {
		        this._item = value;
		    }
		}
		
		private Vendor _vendor;
		public virtual Vendor Vendor 
		{ 
		    get
		    {
		        return this._vendor;
		    }
		    set
		    {
		        this._vendor = value;
		    }
		}
		
	}
}
