#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OimsDataModel;


namespace OimsDataModel	
{
	public partial class Request
	{
		private int _o_Id;
		public virtual int O_Id 
		{ 
		    get
		    {
		        return this._o_Id;
		    }
		    set
		    {
		        this._o_Id = value;
		    }
		}
		
		private int _o_CreatedBy;
		public virtual int O_CreatedBy 
		{ 
		    get
		    {
		        return this._o_CreatedBy;
		    }
		    set
		    {
		        this._o_CreatedBy = value;
		    }
		}
		
		private DateTime _o_CreatedDate;
		public virtual DateTime O_CreatedDate 
		{ 
		    get
		    {
		        return this._o_CreatedDate;
		    }
		    set
		    {
		        this._o_CreatedDate = value;
		    }
		}
		
		private int? _o_UpdatedBy;
		public virtual int? O_UpdatedBy 
		{ 
		    get
		    {
		        return this._o_UpdatedBy;
		    }
		    set
		    {
		        this._o_UpdatedBy = value;
		    }
		}
		
		private DateTime? _o_UpdatedDate;
		public virtual DateTime? O_UpdatedDate 
		{ 
		    get
		    {
		        return this._o_UpdatedDate;
		    }
		    set
		    {
		        this._o_UpdatedDate = value;
		    }
		}
		
		private string _o_Job;
		public virtual string O_Job 
		{ 
		    get
		    {
		        return this._o_Job;
		    }
		    set
		    {
		        this._o_Job = value;
		    }
		}
		
		private int _o_Status;
		public virtual int O_Status 
		{ 
		    get
		    {
		        return this._o_Status;
		    }
		    set
		    {
		        this._o_Status = value;
		    }
		}
		
		private string _o_Company;
		public virtual string O_Company 
		{ 
		    get
		    {
		        return this._o_Company;
		    }
		    set
		    {
		        this._o_Company = value;
		    }
		}
		
		private Company _company;
		public virtual Company Company 
		{ 
		    get
		    {
		        return this._company;
		    }
		    set
		    {
		        this._company = value;
		    }
		}
		
		private Requeststatus _requeststatus;
		public virtual Requeststatus Requeststatus 
		{ 
		    get
		    {
		        return this._requeststatus;
		    }
		    set
		    {
		        this._requeststatus = value;
		    }
		}
		
		private User _user;
		public virtual User User 
		{ 
		    get
		    {
		        return this._user;
		    }
		    set
		    {
		        this._user = value;
		    }
		}
		
		private IList<Sheltersrequest> _sheltersrequests = new List<Sheltersrequest>();
		public virtual IList<Sheltersrequest> Sheltersrequests 
		{ 
		    get
		    {
		        return this._sheltersrequests;
		    }
		}
		
		private IList<Itemsrequest> _itemsrequests = new List<Itemsrequest>();
		public virtual IList<Itemsrequest> Itemsrequests 
		{ 
		    get
		    {
		        return this._itemsrequests;
		    }
		}
		
		private IList<Allocated> _allocateds = new List<Allocated>();
		public virtual IList<Allocated> Allocateds 
		{ 
		    get
		    {
		        return this._allocateds;
		    }
		}
		
	}
}
