#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OimsDataModel;


namespace OimsDataModel	
{
	public partial class Sheltersrequest
	{
		private int _oP_Id;
		public virtual int OP_Id 
		{ 
		    get
		    {
		        return this._oP_Id;
		    }
		    set
		    {
		        this._oP_Id = value;
		    }
		}
		
		private int _o_Id;
		public virtual int O_Id 
		{ 
		    get
		    {
		        return this._o_Id;
		    }
		    set
		    {
		        this._o_Id = value;
		    }
		}
		
		private int _p_Id;
		public virtual int P_Id 
		{ 
		    get
		    {
		        return this._p_Id;
		    }
		    set
		    {
		        this._p_Id = value;
		    }
		}
		
		private float _oP_Quantity;
		public virtual float OP_Quantity 
		{ 
		    get
		    {
		        return this._oP_Quantity;
		    }
		    set
		    {
		        this._oP_Quantity = value;
		    }
		}
		
		private int? _oP_ProdRecom;
		public virtual int? OP_ProdRecom 
		{ 
		    get
		    {
		        return this._oP_ProdRecom;
		    }
		    set
		    {
		        this._oP_ProdRecom = value;
		    }
		}
		
		private int? _oP_Pending;
		public virtual int? OP_Pending 
		{ 
		    get
		    {
		        return this._oP_Pending;
		    }
		    set
		    {
		        this._oP_Pending = value;
		    }
		}
		
		private int? _oP_ProdAlloc;
		public virtual int? OP_ProdAlloc 
		{ 
		    get
		    {
		        return this._oP_ProdAlloc;
		    }
		    set
		    {
		        this._oP_ProdAlloc = value;
		    }
		}
		
		private int _oP_CreatedBy;
		public virtual int OP_CreatedBy 
		{ 
		    get
		    {
		        return this._oP_CreatedBy;
		    }
		    set
		    {
		        this._oP_CreatedBy = value;
		    }
		}
		
		private DateTime _oP_CreatedDate;
		public virtual DateTime OP_CreatedDate 
		{ 
		    get
		    {
		        return this._oP_CreatedDate;
		    }
		    set
		    {
		        this._oP_CreatedDate = value;
		    }
		}
		
		private int? _oP_UpdatedBy;
		public virtual int? OP_UpdatedBy 
		{ 
		    get
		    {
		        return this._oP_UpdatedBy;
		    }
		    set
		    {
		        this._oP_UpdatedBy = value;
		    }
		}
		
		private DateTime? _oP_UpdatedDate;
		public virtual DateTime? OP_UpdatedDate 
		{ 
		    get
		    {
		        return this._oP_UpdatedDate;
		    }
		    set
		    {
		        this._oP_UpdatedDate = value;
		    }
		}
		
		private Shelter _shelter;
		public virtual Shelter Shelter 
		{ 
		    get
		    {
		        return this._shelter;
		    }
		    set
		    {
		        this._shelter = value;
		    }
		}
		
		private Request _request;
		public virtual Request Request 
		{ 
		    get
		    {
		        return this._request;
		    }
		    set
		    {
		        this._request = value;
		    }
		}
		
	}
}
